export interface ISelectOption {
  label: string;
  value: string;
}

export interface ITile extends ISelectOption {
  key: keyof IParamsFormData;
  rawValue: string;
  selectLabel?: string;
}

export interface ISelectNames {
  cr: string;
  tbs: string;
  hl: string;
  lr: string;
}

export enum ESelectNames {
  CR = "cr",
  TBS = "tbs",
  HL = "hl",
  LR = "lr",
}

export interface IParamsFormData extends ISelectNames {
  start: string;
  as_epq: string;
  as_filetype: string;
  num: string;
  as_sitesearch: string;
  as_eq: string;
}

export const defaultSelectOptions: Record<
  keyof ISelectNames,
  ISelectOption | null
> = {
  tbs: { label: chrome.i18n.getMessage("tbsLabel"), value: "" },
  lr: { label: chrome.i18n.getMessage("lrLabel"), value: "" },
  hl: { label: chrome.i18n.getMessage("hlLabel"), value: "" },
  cr: { label: chrome.i18n.getMessage("crLabel"), value: "" },
};

export const tbsOptions: ISelectOption[] = [
  { label: chrome.i18n.getMessage("tbsOptionLastHour"), value: "qdr:h" },
  { label: chrome.i18n.getMessage("tbsOptionLastDay"), value: "qdr:d" },
  { label: chrome.i18n.getMessage("tbsOptionLastWeek"), value: "qdr:w" },
  { label: chrome.i18n.getMessage("tbsOptionLastMonth"), value: "qdr:m" },
  { label: chrome.i18n.getMessage("tbsOptionLastYear"), value: "qdr:y" },
];

export const crOptions: ISelectOption[] = [
  { label: "Afghanistan", value: "countryAF" },
  { label: "Albania", value: "countryAL" },
  { label: "Algeria", value: "countryDZ" },
  { label: "American Samoa", value: "countryAS" },
  { label: "Andorra", value: "countryAD" },
  { label: "Angola", value: "countryAO" },
  { label: "Anguilla", value: "countryAI" },
  { label: "Antarctica", value: "countryAQ" },
  { label: "Antigua and Barbuda", value: "countryAG" },
  { label: "Argentina", value: "countryAR" },
  { label: "Armenia", value: "countryAM" },
  { label: "Aruba", value: "countryAW" },
  { label: "Australia", value: "countryAU" },
  { label: "Austria", value: "countryAT" },
  { label: "Azerbaijan", value: "countryAZ" },
  { label: "Bahamas", value: "countryBS" },
  { label: "Bahrain", value: "countryBH" },
  { label: "Bangladesh", value: "countryBD" },
  { label: "Barbados", value: "countryBB" },
  { label: "Belarus", value: "countryBY" },
  { label: "Belgium", value: "countryBE" },
  { label: "Belize", value: "countryBZ" },
  { label: "Benin", value: "countryBJ" },
  { label: "Bermuda", value: "countryBM" },
  { label: "Bhutan", value: "countryBT" },
  { label: "Bolivia", value: "countryBO" },
  { label: "Bosnia and Herzegovina", value: "countryBA" },
  { label: "Botswana", value: "countryBW" },
  { label: "Brazil", value: "countryBR" },
  { label: "British Indian Ocean Territory", value: "countryIO" },
  { label: "British Virgin Islands", value: "countryVG" },
  { label: "Brunei", value: "countryBN" },
  { label: "Bulgaria", value: "countryBG" },
  { label: "Burkina Faso", value: "countryBF" },
  { label: "Burundi", value: "countryBI" },
  { label: "Cambodia", value: "countryKH" },
  { label: "Cameroon", value: "countryCM" },
  { label: "Canada", value: "countryCA" },
  { label: "Cape Verde", value: "countryCV" },
  { label: "Cayman Islands", value: "countryKY" },
  { label: "Central African Republic", value: "countryCF" },
  { label: "Chad", value: "countryTD" },
  { label: "Chile", value: "countryCL" },
  { label: "China", value: "countryCN" },
  { label: "Christmas Island", value: "countryCX" },
  { label: "Cocos (Keeling) Islands", value: "countryCC" },
  { label: "Colombia", value: "countryCO" },
  { label: "Comoros", value: "countryKM" },
  { label: "Congo, Democratic Republic of the", value: "countryCD" },
  { label: "Congo, Republic of the", value: "countryCG" },
  { label: "Cook Islands", value: "countryCK" },
  { label: "Costa Rica", value: "countryCR" },
  { label: "Côte d'Ivoire", value: "countryCI" },
  { label: "Croatia", value: "countryHR" },
  { label: "Cuba", value: "countryCU" },
  { label: "Curaçao", value: "countryCW" },
  { label: "Cyprus", value: "countryCY" },
  { label: "Czech Republic", value: "countryCZ" },
  { label: "Denmark", value: "countryDK" },
  { label: "Djibouti", value: "countryDJ" },
  { label: "Dominica", value: "countryDM" },
  { label: "Dominican Republic", value: "countryDO" },
  { label: "Ecuador", value: "countryEC" },
  { label: "Egypt", value: "countryEG" },
  { label: "El Salvador", value: "countrySV" },
  { label: "Equatorial Guinea", value: "countryGQ" },
  { label: "Eritrea", value: "countryER" },
  { label: "Estonia", value: "countryEE" },
  { label: "Ethiopia", value: "countryET" },
  { label: "Falkland Islands", value: "countryFK" },
  { label: "Faroe Islands", value: "countryFO" },
  { label: "Fiji", value: "countryFJ" },
  { label: "Finland", value: "countryFI" },
  { label: "France", value: "countryFR" },
  { label: "French Polynesia", value: "countryPF" },
  { label: "Gabon", value: "countryGA" },
  { label: "Gambia", value: "countryGM" },
  { label: "Georgia", value: "countryGE" },
  { label: "Germany", value: "countryDE" },
  { label: "Ghana", value: "countryGH" },
  { label: "Gibraltar", value: "countryGI" },
  { label: "Greece", value: "countryGR" },
  { label: "Greenland", value: "countryGL" },
  { label: "Grenada", value: "countryGD" },
  { label: "Guam", value: "countryGU" },
  { label: "Guatemala", value: "countryGT" },
  { label: "Guernsey", value: "countryGG" },
  { label: "Guinea", value: "countryGN" },
  { label: "Guinea-Bissau", value: "countryGW" },
  { label: "Guyana", value: "countryGY" },
  { label: "Haiti", value: "countryHT" },
  { label: "Honduras", value: "countryHN" },
  { label: "Hong Kong", value: "countryHK" },
  { label: "Hungary", value: "countryHU" },
  { label: "Iceland", value: "countryIS" },
  { label: "India", value: "countryIN" },
  { label: "Indonesia", value: "countryID" },
  { label: "Iran", value: "countryIR" },
  { label: "Iraq", value: "countryIQ" },
  { label: "Ireland", value: "countryIE" },
  { label: "Isle of Man", value: "countryIM" },
  { label: "Israel", value: "countryIL" },
  { label: "Italy", value: "countryIT" },
  { label: "Jamaica", value: "countryJM" },
  { label: "Japan", value: "countryJP" },
  { label: "Jersey", value: "countryJE" },
  { label: "Jordan", value: "countryJO" },
  { label: "Kazakhstan", value: "countryKZ" },
  { label: "Kenya", value: "countryKE" },
  { label: "Kiribati", value: "countryKI" },
  { label: "Korea, North", value: "countryKP" },
  { label: "Korea, South", value: "countryKR" },
  { label: "Kuwait", value: "countryKW" },
  { label: "Kyrgyzstan", value: "countryKG" },
  { label: "Laos", value: "countryLA" },
  { label: "Latvia", value: "countryLV" },
  { label: "Lebanon", value: "countryLB" },
  { label: "Lesotho", value: "countryLS" },
  { label: "Liberia", value: "countryLR" },
  { label: "Libya", value: "countryLY" },
  { label: "Liechtenstein", value: "countryLI" },
  { label: "Lithuania", value: "countryLT" },
  { label: "Luxembourg", value: "countryLU" },
  { label: "Macau", value: "countryMO" },
  { label: "Macedonia", value: "countryMK" },
  { label: "Madagascar", value: "countryMG" },
  { label: "Malawi", value: "countryMW" },
  { label: "Malaysia", value: "countryMY" },
  { label: "Maldives", value: "countryMV" },
  { label: "Mali", value: "countryML" },
  { label: "Malta", value: "countryMT" },
  { label: "Marshall Islands", value: "countryMH" },
  { label: "Mauritania", value: "countryMR" },
  { label: "Mauritius", value: "countryMU" },
  { label: "Mayotte", value: "countryYT" },
  { label: "Mexico", value: "countryMX" },
  { label: "Micronesia", value: "countryFM" },
  { label: "Moldova", value: "countryMD" },
  { label: "Monaco", value: "countryMC" },
  { label: "Mongolia", value: "countryMN" },
  { label: "Montenegro", value: "countryME" },
  { label: "Montserrat", value: "countryMS" },
  { label: "Morocco", value: "countryMA" },
  { label: "Mozambique", value: "countryMZ" },
  { label: "Myanmar", value: "countryMM" },
  { label: "Namibia", value: "countryNA" },
  { label: "Nauru", value: "countryNR" },
  { label: "Nepal", value: "countryNP" },
  { label: "Netherlands", value: "countryNL" },
  { label: "New Caledonia", value: "countryNC" },
  { label: "New Zealand", value: "countryNZ" },
  { label: "Nicaragua", value: "countryNI" },
  { label: "Niger", value: "countryNE" },
  { label: "Nigeria", value: "countryNG" },
  { label: "Niue", value: "countryNU" },
  { label: "Norfolk Island", value: "countryNF" },
  { label: "Northern Mariana Islands", value: "countryMP" },
  { label: "Norway", value: "countryNO" },
  { label: "Oman", value: "countryOM" },
  { label: "Pakistan", value: "countryPK" },
  { label: "Palau", value: "countryPW" },
  { label: "Palestine", value: "countryPS" },
  { label: "Panama", value: "countryPA" },
  { label: "Papua New Guinea", value: "countryPG" },
  { label: "Paraguay", value: "countryPY" },
  { label: "Peru", value: "countryPE" },
  { label: "Philippines", value: "countryPH" },
  { label: "Poland", value: "countryPL" },
  { label: "Portugal", value: "countryPT" },
  { label: "Puerto Rico", value: "countryPR" },
  { label: "Qatar", value: "countryQA" },
  { label: "Réunion", value: "countryRE" },
  { label: "Romania", value: "countryRO" },
  { label: "Russia", value: "countryRU" },
  { label: "Rwanda", value: "countryRW" },
  { label: "Saint Helena", value: "countrySH" },
  { label: "Saint Kitts and Nevis", value: "countryKN" },
  { label: "Saint Lucia", value: "countryLC" },
  { label: "Saint Pierre and Miquelon", value: "countryPM" },
  { label: "Saint Vincent and the Grenadines", value: "countryVC" },
  { label: "Samoa", value: "countryWS" },
  { label: "San Marino", value: "countrySM" },
  { label: "Saudi Arabia", value: "countrySA" },
  { label: "Senegal", value: "countrySN" },
  { label: "Serbia", value: "countryRS" },
  { label: "Seychelles", value: "countrySC" },
  { label: "Sierra Leone", value: "countrySL" },
  { label: "Singapore", value: "countrySG" },
  { label: "Sint Maarten", value: "countrySX" },
  { label: "Slovakia", value: "countrySK" },
  { label: "Slovenia", value: "countrySI" },
  { label: "Solomon Islands", value: "countrySB" },
  { label: "Somalia", value: "countrySO" },
  { label: "South Africa", value: "countryZA" },
  { label: "Spain", value: "countryES" },
  { label: "Sri Lanka", value: "countryLK" },
  { label: "Sudan", value: "countrySD" },
  { label: "Suriname", value: "countrySR" },
  { label: "Swaziland", value: "countrySZ" },
  { label: "Sweden", value: "countrySE" },
  { label: "Switzerland", value: "countryCH" },
  { label: "Syria", value: "countrySY" },
  { label: "Taiwan", value: "countryTW" },
  { label: "Tajikistan", value: "countryTJ" },
  { label: "Tanzania", value: "countryTZ" },
  { label: "Thailand", value: "countryTH" },
  { label: "Togo", value: "countryTG" },
  { label: "Tokelau", value: "countryTK" },
  { label: "Tonga", value: "countryTO" },
  { label: "Trinidad and Tobago", value: "countryTT" },
  { label: "Tunisia", value: "countryTN" },
  { label: "Turkey", value: "countryTR" },
  { label: "Turkmenistan", value: "countryTM" },
  { label: "Turks and Caicos Islands", value: "countryTC" },
  { label: "Tuvalu", value: "countryTV" },
  { label: "Uganda", value: "countryUG" },
  { label: "Ukraine", value: "countryUA" },
  { label: "United Arab Emirates", value: "countryAE" },
  { label: "United Kingdom", value: "countryGB" },
  { label: "United States", value: "countryUS" },
  { label: "Uruguay", value: "countryUY" },
  { label: "Uzbekistan", value: "countryUZ" },
  { label: "Vanuatu", value: "countryVU" },
  { label: "Vatican City", value: "countryVA" },
  { label: "Venezuela", value: "countryVE" },
  { label: "Vietnam", value: "countryVN" },
  { label: "Wallis and Futuna Islands", value: "countryWF" },
  { label: "Yemen", value: "countryYE" },
  { label: "Zambia", value: "countryZM" },
  { label: "Zimbabwe", value: "countryZW" },
];

export const hlOptions: ISelectOption[] = [
  { value: "af", label: "Afrikaans" },
  { value: "sq", label: "Albanian" },
  { value: "ar", label: "Arabic" },
  { value: "hy", label: "Armenian" },
  { value: "bn", label: "Bengali" },
  { value: "bs", label: "Bosnian" },
  { value: "ca", label: "Catalan" },
  { value: "hr", label: "Croatian" },
  { value: "cs", label: "Czech" },
  { value: "da", label: "Danish" },
  { value: "nl", label: "Dutch" },
  { value: "en", label: "English" },
  { value: "eo", label: "Esperanto" },
  { value: "et", label: "Estonian" },
  { value: "tl", label: "Filipino" },
  { value: "fi", label: "Finnish" },
  { value: "fr", label: "French" },
  { value: "de", label: "German" },
  { value: "el", label: "Greek" },
  { value: "gu", label: "Gujarati" },
  { value: "hi", label: "Hindi" },
  { value: "hu", label: "Hungarian" },
  { value: "id", label: "Indonesian" },
  { value: "it", label: "Italian" },
  { value: "ja", label: "Japanese" },
  { value: "jw", label: "Javanese" },
  { value: "ka", label: "Georgian" },
  { value: "km", label: "Khmer" },
  { value: "kn", label: "Kannada" },
  { value: "ko", label: "Korean" },
  { value: "la", label: "Latin" },
  { value: "lv", label: "Latvian" },
  { value: "lt", label: "Lithuanian" },
  { value: "mk", label: "Macedonian" },
  { value: "ml", label: "Malayalam" },
  { value: "mr", label: "Marathi" },
  { value: "my", label: "Burmese" },
  { value: "ne", label: "Nepali" },
  { value: "no", label: "Norwegian" },
  { value: "pl", label: "Polish" },
  { value: "pt", label: "Portuguese" },
  { value: "pa", label: "Punjabi" },
  { value: "ro", label: "Romanian" },
  { value: "ru", label: "Russian" },
  { value: "sr", label: "Serbian" },
  { value: "si", label: "Sinhala" },
  { value: "sk", label: "Slovak" },
  { value: "sl", label: "Slovenian" },
  { value: "es", label: "Spanish" },
  { value: "su", label: "Sundanese" },
  { value: "sv", label: "Swedish" },
  { value: "ta", label: "Tamil" },
  { value: "te", label: "Telugu" },
  { value: "th", label: "Thai" },
  { value: "tr", label: "Turkish" },
  { value: "uk", label: "Ukrainian" },
  { value: "ur", label: "Urdu" },
  { value: "vi", label: "Vietnamese" },
  { value: "cy", label: "Welsh" },
  { value: "zh-CN", label: "Chinese (Simplified)" },
  { value: "zh-TW", label: "Chinese (Traditional)" },
];

export const lrOptions: ISelectOption[] = hlOptions.map((opt) => ({
  ...opt,
  value: `lang_${opt.value}`,
}));

export const labelTexts = {
  start: "Show from element",
  as_epq: "Exact phrase",
  as_filetype: "Search for file types",
  lr: defaultSelectOptions.lr!.label,
  hl: defaultSelectOptions.hl!.label,
  num: "Show per page",
  as_sitesearch: "Restrict results to site",
  as_eq: "Exclude words",
  cr: defaultSelectOptions.cr!.label,
  tbs: defaultSelectOptions.tbs!.label,
};

export const BackgroundActions = {
  getStorage: "getStorage",
  setStorage: "setStorage",
};

export const ChromeStorageKeys = {
  tiles: "chromeStorageTiles",
};
